LeapAtTargetBehaviour
Tslat/SmartBrainLib pull request #70
Opened 2024-08-29 03:42 UTC by OmbreMoon

Recreation of the LeapAtTargetGoal for the brain system

2024-08-29 06:26 UTC, Tslat requested changes
The rest is arbitrary stuff I can clean up before push

2024-08-29 06:26 UTC, Tslat commented on Common/src/main/java/net/tslat/smartbrainlib/api/core/behaviour/custom/attack/LeapAtTargetBehavior.java
> +        Vec3 vec32 = new Vec3(this.target.getX() - entity.getX(), 0.0, this.target.getZ() - entity.getZ());
Can we give our variables useful names please

2024-08-29 06:26 UTC, Tslat commented on Common/src/main/java/net/tslat/smartbrainlib/api/core/behaviour/custom/attack/LeapAtTargetBehavior.java
> +            vec32 = vec32.normalize().scale(0.4).add(vec3.scale(0.2));
Magic numbers for dynamic behaviour?

2024-08-29 07:03 UTC, OmbreMoon commented
Will fix all that tomorrow, it's midnight here

2024-08-31 05:58 UTC, Tslat approved these changes

2024-08-31 13:56 UTC, merged